### ISSUE TITLE
Error line 229

### ISSUE THREAD

**Issue by Leviaudev** [infotrex/bulk-upload-to-opensea#64]
C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main>python upload18.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload18.py", line 229, in main_program_loop
    driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt, )
TypeError: __init__() got an unexpected keyword argument 'service'

**Comment by ZacharyAkers** [comment]
@Leviaudev check that on line 24-25 what is put is 
`from selenium.webdriver.chrome.options import Options`
`from selenium.webdriver.chrome.service import Service`

**Comment by Leviaudev** [comment]
> @Leviaudev check that on line 24-25 what is put is `from selenium.webdriver.chrome.options import Options` `from selenium.webdriver.chrome.service import Service`

Thanks for your reply: My imports are: 

```
import tkinter
import subprocess
from tkinter import *
from tkinter import filedialog
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
import tkinter.font as font
from turtle import width
from PIL import ImageTk, Image
import urllib.request
from io import BytesIO
import os
import io
import sys
import pickle
import time
from decimal import *
import webbrowser
# from click import command
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support import expected_conditions as ExpectedConditions
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import timedelta  
from dateutil.relativedelta import relativedelta
from datetime import timedelta, date
import locale
import json 
import ssl
```

I dont know why I have this error :c

**Comment by ZacharyAkers** [comment]
@Leviaudev  Weird it should be working then..can you copy what you have from 222-230

**Comment by Leviaudev** [comment]
> @Leviaudev Weird it should be working then..can you copy what you have from 222-230

Yeah, i have download the last version, it should work :o

`    ##chromeoptions
    opt = Options()
    opt.add_argument('--headless')
    opt.add_experimental_option("debuggerAddress", "localhost:8989")
    # driver = webdriver.Chrome(
    #     executable_path=project_path + "/chromedriver.exe",
    #     chrome_options=opt,
    # )
    driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt, )
    wait = WebDriverWait(driver, 60)`

**Comment by ZacharyAkers** [comment]
copy over your imports from 1-34
```import tkinter
import subprocess
from tkinter import *
from tkinter import filedialog
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
import tkinter.font as font
from turtle import width
from PIL import ImageTk, Image
import urllib.request
from io import BytesIO
import os
import io
import sys
import pickle
import time
from decimal import *
import webbrowser
# from click import command
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support import expected_conditions as ExpectedConditions
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import timedelta  
from dateutil.relativedelta import relativedelta
from datetime import timedelta, date
import locale
import json 
import ssl```

copy over line 222-230
``` opt = Options()
    opt.add_argument('--headless')
    opt.add_experimental_option("debuggerAddress", "localhost:8989")
    driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt,)
    wait = WebDriverWait(driver, 60)```

**Comment by ZacharyAkers** [comment]
Double checked it was working on my end, maybe there is something just slightly off

**Comment by Leviaudev** [comment]
> copy over your imports from 1-34
> 
> ```
> import subprocess
> from tkinter import *
> from tkinter import filedialog
> import tkinter as tk
> from tkinter import ttk
> from tkinter import messagebox
> import tkinter.font as font
> from turtle import width
> from PIL import ImageTk, Image
> import urllib.request
> from io import BytesIO
> import os
> import io
> import sys
> import pickle
> import time
> from decimal import *
> import webbrowser
> # from click import command
> from selenium import webdriver
> from selenium.webdriver.common.by import By
> from selenium.webdriver.support.wait import WebDriverWait
> from selenium.webdriver.chrome.options import Options
> from selenium.webdriver.chrome.service import Service
> from selenium.webdriver.support import expected_conditions as ExpectedConditions
> from selenium.webdriver.support.ui import Select
> from selenium.webdriver.common.keys import Keys
> from datetime import timedelta  
> from dateutil.relativedelta import relativedelta
> from datetime import timedelta, date
> import locale
> import json 
> import ssl```
> 
> copy over line 222-230
> ``` opt = Options()
>     opt.add_argument('--headless')
>     opt.add_experimental_option("debuggerAddress", "localhost:8989")
>     driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt,)
>     wait = WebDriverWait(driver, 60)```
> ```

Done, i have the same error:

```
C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main>python upload18.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload18.py", line 225, in main_program_loop
    driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt,)
TypeError: __init__() got an unexpected keyword argument 'service'
```

**Comment by ZacharyAkers** [comment]
ok lets do this then do in terminal `pip install -U selenium`

**Comment by ZacharyAkers** [comment]
if that doesn't work just put this instead
opt = Options()
opt.add_argument('--headless')
opt.add_experimental_option("debuggerAddress", "localhost:8989")
driver = webdriver.Chrome(
executable_path=project_path + "/chromedriver.exe",
chrome_options=opt,
)
# driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt, )
wait = WebDriverWait(driver, 60)

**Comment by ZacharyAkers** [comment]
you will still get depreciation warnings but itll work till i can figure out what is causing issue. if you do 2nd solution

**Comment by Leviaudev** [comment]
> ok lets do this then do in terminal `pip install -U selenium` to make sure your selenium is up to date then try running it

C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main>pip show selenium
Name: selenium
Version: 4.1.0


C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload18.py:225: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(

**Comment by Leviaudev** [comment]
> > ok lets do this then do in terminal `pip install -U selenium` to make sure your selenium is up to date then try running it
> 
> C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main>pip show selenium Name: selenium Version: 4.1.0
> 
> C:\Users\thoma\Desktop\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload18.py:225: DeprecationWarning: executable_path has been deprecated, please pass in a Service object driver = webdriver.Chrome(

It's really strange, when I run the software, it goes to the opensea homepage, then does nothing

**Comment by ZacharyAkers** [comment]
> if that doesn't work just put this instead opt = Options() opt.add_argument('--headless') opt.add_experimental_option("debuggerAddress", "localhost:8989") driver = webdriver.Chrome( executable_path=project_path + "/chromedriver.exe", chrome_options=opt, ) wait = WebDriverWait(driver, 60)

@Leviaudev did you try this method to see if it works for you?

**Comment by ZacharyAkers** [comment]
well im stumped on why it isnt working then lol

**Comment by Leviaudev** [comment]
It's ok, I can still use the old version  ^_^

**Comment by Leviaudev** [comment]
oh noo the old version dont work too XD

`<string>:211: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
<string>:211: DeprecationWarning: use options instead of chrome_options`
Running do nothing :o

**Comment by Leviaudev** [comment]
Windows 10.

I was using the old version without any problem, I came to update the software because I saw that I had a little driver problem on chrome  (many of us have had this problem)

However, nothing has changed on my pc, and I haven't updated anything except this github folder

**Comment by ZacharyAkers** [comment]
I reinstalled and tried with code again and it works.. weird you are using the open chrome browser button on app right?

**Comment by infotrex** [comment]
@Leviaudev,
pls cross check your PC chrome version
and download compatible version and replace chromedriver.exe this file
https://chromedriver.chromium.org/downloads

thx

**Comment by Leviaudev** [comment]
It finally works! I think the bug comes from the "Save this form" button
This saved data from version 1 to version 18.
I'm no expert in python, but I think this must have caused interference

**Comment by ZacharyAkers** [comment]
wait trying to understand the exact issue. You never pressed save this form after adding the new code?

**Comment by Leviaudev** [comment]
No, i have never pressed it. I have delete it and now it's work
